#!/bin/bash

set -u
set -e
echo "File location $0"
echo "plugin_dir = $plugin_dir/"

source "./functions"
if [ -f "$plugin_dir/functions" ]; then
    echo "<<<<<functions file exists>>>>>>>"
fi
source "$plugin_dir/functions"

create_app_skel
install_app
write_config
write_control
install_app_gems
