#!/bin/sh
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config

echo "*** Changing default port 8080 for torquebox to $port ***"

echo "Assuming Ruby1.9 :( should be configurable :( "

echo torquebox run -J="-Djboss.web.http.port=$port"

#exec jruby --1.9 -S torquebox run
exec torquebox run -J="-Djboss.web.http.port=$port" 